---
title: "GARCH parameters and quantiles estimation"
author: "Jose Augusto Fiorucci"
date: "20/11/2020"
output: pdf_document
---

```{r setup, include=FALSE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE)
require(quantmod)
options("getSymbols.warning4.0"=FALSE)
require(magrittr)
require(fGarch)
require(bayesDccGarch) #https://github.com/jafiorucci/bayesDccGarch/blob/main/bayesDccGarch_2.1.tar.gz
set.seed(9999)
```


# Input
```{r, echo=TRUE}
symbol = "BOVA11.SA"
from=as.Date('2012-01-01')
to=as.Date('2018-12-31')
C_Trend = 0.95
C_Reaction = 0.50
```

# Data download
```{r, echo=TRUE}
getSymbols.yahoo(symbol, from=from, to=to, env=globalenv())
x <- get(symbol, envir=globalenv())
rm(list = symbol, envir=globalenv())
```


## High and Low
```{r, echo=TRUE, fig.height=4, out.width = '50%', fig.align = "center"}
H <- Hi(x)
L <- Lo(x)
plot(cbind(H,L))
```


## Returns
```{r, echo=TRUE, fig.height=4, out.width = '50%', fig.align = "center"}
y <- cbind( diff(log(H)),  diff(log(L)) )
y <- na.omit(y)
y %>% cor() # Returns correlation
plot(y)
```


## Autocorrelation
```{r, echo=TRUE, fig.height=4, out.width = '50%', fig.align = "center"}
acf(y[,1])
acf(y[,2])
```



## Cross correlation
```{r, echo=TRUE, fig.height=4, out.width = '50%', fig.align = "center"}
ccf(as.ts(y[,1]),as.ts(y[,2]))
```


## Volatility verification
```{r, echo=TRUE, fig.height=4, out.width = '50%', fig.align = "center"}
acf(y[,1]^2)
acf(y[,2]^2)
```


<!-- ######################################################################### -->

# Bivariate DCC-GARCH

We will consider the DCC-GARCH to model the volatility of $y = (r_H, r_L)'$, where $r_H$ and $r_L$ denote the $100\times$log-returns from hight's and low's observations.

```{r, echo=TRUE, out.width = '90%', fig.align = "center"}
# returns
mY <- 100*y 

# generates the Markov Chain
start <- Sys.time()

out <- bayesDccGarch(mY, control=list(print=FALSE))

out2 <- increaseSim(out, nSim=50000)
	
out <- window(out2, start=20000, thin=10)
rm(out2)

end <- Sys.time()

# elapsed time
end-start

# plot Markov Chain
plot(out$MC)

## Estimative of parameters
out$MC %>% summary() 


# Prepare input for the expert advisor	
parEst <- summary(out)$statistics[,'Mean']
	
## High
#HBOP
High_UB_HBOP = qsstd(p=1-(1-C_Trend)/2, mean = 0, sd = 1, nu = parEst['nu'], xi = parEst['gamma_1'])
#S1
High_UB_S1 = qsstd(p=1-(1-C_Reaction)/2, mean = 0, sd = 1, nu = parEst['nu'], xi = parEst['gamma_1'])


## Low
#B1
Low_LB_B1 = qsstd(p=(1-C_Reaction)/2, mean = 0, sd = 1, nu = parEst['nu'], xi = parEst['gamma_2'])
#LBOP
Low_LB_LBOP = qsstd(p=(1-C_Trend)/2, mean = 0, sd = 1, nu = parEst['nu'], xi = parEst['gamma_2'])


m = matrix(NA,nrow=10,ncol=1)
rownames(m) = c("High_UB_HBOP","High_UB_S1","Low_LB_B1","Low_LB_LBOP",
               "High_omega", "High_alpha","High_beta",
			         "Low_omega",  "Low_alpha", "Low_beta" )
colnames(m) = 'Value'

m["High_UB_HBOP",1] = High_UB_HBOP
m["High_UB_S1",1] = High_UB_S1
m["Low_LB_B1",1] =  Low_LB_B1
m["Low_LB_LBOP",1] = Low_LB_LBOP

m["High_omega",1] = parEst["omega_1"]
m["High_alpha",1] = parEst["alpha_1"]
m["High_beta",1] = parEst["beta_1"]

m["Low_omega",1] = parEst["omega_2"]
m["Low_alpha",1] = parEst["alpha_2"]
m["Low_beta",1] = parEst["beta_2"]

# Input for expert advisor
print(round(m,3))
```

